
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0Nano_NIOSII(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////////// KEY //////////
	KEY,

	//////////// SW //////////
	SW,

	//////////// SDRAM //////////
	DRAM_ADDR,
	DRAM_BA,
	DRAM_CAS_N,
	DRAM_CKE,
	DRAM_CLK,
	DRAM_CS_N,
	DRAM_DQ,
	DRAM_DQM,
	DRAM_RAS_N,
	DRAM_WE_N,

	//////////// EPCS //////////
	EPCS_ASDO,
	EPCS_DATA0,
	EPCS_DCLK,
	EPCS_NCSO,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	GPIO_0,
	GPIO_0_IN 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;

//////////// LED //////////
output		     [7:0]		LED;

//////////// KEY //////////
input 		     [1:0]		KEY;

//////////// SW //////////
input 		     [3:0]		SW;

//////////// SDRAM //////////
output		    [12:0]		DRAM_ADDR;
output		     [1:0]		DRAM_BA;
output		          		DRAM_CAS_N;
output		          		DRAM_CKE;
output		          		DRAM_CLK;
output		          		DRAM_CS_N;
inout 		    [15:0]		DRAM_DQ;
output		     [1:0]		DRAM_DQM;
output		          		DRAM_RAS_N;
output		          		DRAM_WE_N;

//////////// EPCS //////////
output		          		EPCS_ASDO;
input 		          		EPCS_DATA0;
output		          		EPCS_DCLK;
output		          		EPCS_NCSO;

//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
inout 		    [33:0]		GPIO_0;
input 		     [1:0]		GPIO_0_IN;


//=======================================================
//  REG/WIRE declarations
//=======================================================





//=======================================================
//  Structural coding
//=======================================================
    niosII u0 (
        .clk_clk            (CLOCK_50),            //         clk.clk
        .reset_reset_n      (1'b1),      				//       reset.reset_n
        .rs232_0_RXD        (GPIO_0_IN[0]),        //     rs232_0.RXD
        .rs232_0_TXD        (GPIO_0[32]),        //            .TXD
        .rs232_1_RXD        (GPIO_0_IN[1]),        //     rs232_1.RXD
        .rs232_1_TXD        (GPIO_0[33]),         //            .TXD
        .port_led_export    (LED),    					//    port_led.export
        .port_key_export    (KEY),    					//    port_key.export
        .port_sw_export     (SW),     					//     port_sw.export
        .port_gpio_0_export (GPIO_0[31:0]), 			// port_gpio_0.export
        .epcs_dclk          (EPCS_DCLK),          //        epcs.dclk
        .epcs_sce           (EPCS_NCSO),           //            .sce
        .epcs_sdo           (EPCS_ASDO),           //            .sdo
        .epcs_data0         (EPCS_DATA0),         //            .data0
        .sdram_addr         (DRAM_ADDR),         					  //       sdram.addr
        .sdram_ba           (DRAM_BA),           //            .ba
        .sdram_cas_n        (DRAM_CAS_N),        //            .cas_n
        .sdram_cke          (DRAM_CKE),          //            .cke
        .sdram_cs_n         (DRAM_CS_N),         //            .cs_n
        .sdram_dq           (DRAM_DQ),           //            .dq
        .sdram_dqm          (DRAM_DQM),          //            .dqm
        .sdram_ras_n        (DRAM_RAS_N),        //            .ras_n
        .sdram_we_n         (DRAM_WE_N),          //            .we_n
		  .ram_clk_clk        (DRAM_CLK)         //     ram_clk.clk
    );
	
endmodule
